name: movie_magic
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_core: ^3.10.0
  flextras: ^1.0.0
  flutter_animate: ^4.5.2
  flutter_animated_dialog_updated: ^1.0.1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  gap: ^3.0.1
  google_fonts: ^6.3.2
  go_router: ^10.0.0
  hydrated_bloc: ^9.1.5
  intl: ^0.20.2
  json_annotation: ^4.8.0
  loading_overlay: ^0.3.0
  lottie: ^2.2.0
  oktoast: ^3.3.1
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/movie.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/movie_magic.png"
  adaptive_icon_background: "#004D40"
  remove_alpha_ios: true
